library = ["skibidi", "gyatt", "rizz", "in ohio", "ohio",
            "duke dennis", "livvy dunne", "rizzing", "rizz", "baby gronk", "sussy", "imposter", "pibby",
             "sigma", "alpha male", "omega male", "grindset", "andrew tate", "goon cave", "goon",
               "freddy fazbear", "colleen", "ligma","bofa" , "ballinger", "smurf cat", "blud", "dawg", "shmlawg",
                 "ishowspeed", "turbulence", "ambatukam", "griddy",  "ocky way", "kai cenat", "fanum tax"
                   ,"edging", "bussing" "whopper whopper", "goofy ahh", "aiden ross", "sin city", 
                    "goated", "john pork", "grimace shake", "nathaniel b", "lightskin stare", "biggest bird",
                      "omar", "the referee", "amogus", "uncanny", "wholesome", "reddit", "chungus" ,"keanu reeves",
                        "pizza tower", "zesty", "poggers",  "quandale dingle", "glizzy", "ankha zone", "thug shaker", "morbin time",
                        "morb", "dj khaled", "sisyphus", "oceangate",  "t-pose", "ugandan knuckles", "family guy", "nickeh30", "ratio", "uwu", "owo", "delulu"
                          "opium bird", "cg5", "mewing", "fortnite", "backrooms", "gigachad", "based", "cringe", "kino", "redpilled",
                           "bluepilled", "F", "lean", "looksmaxxing", "gassy", "social credit", "bing chilling", "xbox live", "mrbeast"
                              ,"ice spice", "gooning", "fr", "kevin james", "josh hutcherson", "caseoh", "sugma", "kissma", "patrick bateman","discord kitten"
                              ,"rizzler", "cap", "no cap", "hawk tuah", "frfr", "L",'aesthetic', 'bet', 'cap','clout', 'dope', 'extra', 'fam', 'finesse', 'goat', 'hypebeast', 
            'lit af', 'lowkey', 'mood', 'noob', 'on fleek', 'savage', 'shade', 'slay', 'sus', 'tea', 
            'vibe', 'w', 'yas', 'zoned out', 'flexing', 'lit', 'looksmaxxing', 'mid', 'rizz', 'ate', 
            'left no crumbs', 'slayed', 'cringe', 'cringey', 'vibe check', 'hawk tuah', 'catch these hands', 'mewing', 'mog', 'rizzing',
            'dad lore', 'baby gronk', 'livvy dunne', 'kai cenat', 'bussin', 'gyatt', 'gyat', 'rizzler', 'only in ohio', 
            'ick', 'winter arc', 'fanum tax', 'caseoh', 'squad', 'glow up', 'snatched', 'periodt', 'bop', 'drip', 
            'fire', 'ghost', 'hella', 'karen', 'meme', 'ok, boomer', 'pog', 'salty', 'ship', 'szn', 
            'yeet', 'zoomer', 'goon', 'gooner', 'cap', 'simp', 'zesty', 'freaky', 'diddy', 'thicc', 
            'gassed', 'gas', 'bae', 'dab', 'feels', 'hot mess', 'kicks', 'rager', 'swole', 
            'troll', 'l', 'yas queen', 'chillax', 'bussing', 'clapped', 'degen', 'ratchet', 'spicy', 'woke'
            'dank', 'ghosting', 'meme lord', 'flex', 'highkey', 'goated', 'snack', 'poggers', 'skibbidi', 'brainrot', 
            'sigma', 'edging' 'edge lord', 'bruh', 'opp', 'twin', 'ohio', 'pookie', 'og', 'sheesh', 
            'swag', 'dog water', 'yap', 'yapping', 'grimace shake', 'grimace', 'goofy', 'goofy ahh', 'sussy', 'baka', 
            'ligma', 'griddy', 'devious', 'devious lick', 'brokies', 'alpha', 'beta', 'chug jug', 'preppy', 'ishowspeed', 
            'ratio', 'ipad kid', 'andrew tate', 'fatherless', 'cook', 'cooking', 'cooked', 'fortnite', 'among us', 'toxic', 
            'stream', 'camera man', 'ice spice', 'g', 'munch', 'imposter', 'omega', 'male grindset', 'grind', 'freddy fazbear', 
            'smurf cat', 'blud', 'ocky way', 'bing chilling', 'gigachad', 'glizzy', 'gang', 'ayo', 't-pose', 'aesthetic', 'bet', 'cap', 'clout', 'dope', 'extra', 'fam', 'finesse', 'goat', 'hypebeast',
            'lit', 'lowkey', 'mid', 'delulu', 'rizz', 'uwu', 'yeet', 'simp', 'normie', 'dank', 'crunchy',
            'bruh', 'chad', 'sigma', 'alpha', 'zoomer', 'boomer', 'steez', 'bars', 'gyatt', 'abow',
            'streaks', 'thug', 'throuple', 'beef', 'Karen', 'stacy', 'bae', 'choob', 'baller', 'moots',
            'snacc', 'birb', 'bish', 'slaps', 'drip', 'pogue', 'sealioning', 'edgelord', 'pickme',
            'adorkable', 'maskne', 'finesse', 'book', 'boomshakalaka', 'dolo', 'gatekeep', 'lovebomb',
            'softie', 'jawn', 'headcanon', 'sus', 'sksksk', 'shlitty', 'based', 'bollection', 'ded',
            'noob', 'retoast', 'sploot', 'power', 'tea','hello','you','love','.','you.']